"""empty message

Revision ID: 493c406e78c3
Revises: 9b216e3d07d0
Create Date: 2021-07-09 17:29:03.413358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '493c406e78c3'
down_revision = '9b216e3d07d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('last_name', sa.String(length=80), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
