"""empty message

Revision ID: 914ca1455d5f
Revises: 493c406e78c3
Create Date: 2021-07-09 17:32:32.002373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '914ca1455d5f'
down_revision = '493c406e78c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###
